version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Testing
          command: npm run test
      - coveralls/upload:
          path: coverage/lcov.info
workflows:
  main-workflow:
    jobs:
      - build
