version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
          working_directory: client
      - run:
          name: Testing
          command: npm test -- --coverage
          working_directory: client
      - run:
          name: Build application for production
          command: npm run build
          working_directory: client
      - coveralls/upload

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install client local dependencies
          command: npm install
          working_directory: client
      - run:
          name: Testing
          command: npm test -- --coverage
          working_directory: client
      - run:
          name: Create .env file
          command: echo "REACT_APP_API_KEY=${REACT_APP_API_KEY}" >> .env
          working_directory: client
      - run:
          name: Build application for production
          command: npm run build
          working_directory: client
      - run:
          name: Install firebase-tools to client
          command: npm install firebase-tools
          working_directory: client
      - run:
          name: Deploy app to Firebase
          command: ./node_modules/.bin/firebase deploy --only hosting --token ${FIREBASE_TOKEN}
          working_directory: client
      - run:
          name: Install server local dependencies
          command: npm install
          working_directory: server
      - run:
          name: Install firebase-tools to server
          command: npm install firebase-tools
          working_directory: server
      - run:
          name: Create .env file
          command: |
            echo "REACT_APP_API_KEY=${REACT_APP_API_KEY}" >> .env
            echo "EVENTS_API_KEY=${EVENTS_API_KEY}" >> .env
            echo "DINING_API_KEY=${DINING_API_KEY}" >> .env
          working_directory: server
      - run:
          name: Deploy API to Firebase
          command: ./node_modules/.bin/firebase deploy --only functions:api --token ${FIREBASE_TOKEN}
          working_directory: server
      - coveralls/upload

workflows:
  main-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main
