version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Testing
          command: npm test -- --coverage
      - coveralls/upload

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Testing
          command: npm test -- --coverage
      - run:
          name: Build application for production
          command: npm run build
      - run:
          name: Install firebase-tools locally
          command: npm install firebase-tools
      - run:
          name: Deploy app to Firebase
          command: ./node_modules/.bin/firebase deploy --only hosting --token ${FIREBASE_TOKEN}
      - coveralls/upload


workflows:
  main-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
