version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Testing
          command: npm test -- --coverage
      - run:
          name: Build application for production
          command: npm run build
      - coveralls/upload

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Deploy app to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  main-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
